services:
  postfix:
    container_name: postfix
    image: loganmarchione/docker-postfixrelay:latest
    ports:
      - 25:25/tcp
    environment:
      - TZ=Your/Region
      - RELAY_HOST=smtp.office365.com
      - RELAY_PORT=587
      - RELAY_USER=upn@domain.com
      - RELAY_PASS=pass
      - MYORIGIN=yourdomain.com
      - MYNETWORKS=1.1.1.1/1 2.2.2.2/2
    volumes:
      - /mnt/app/db/postfix/queue:/var/spool/postfix
      - /mnt/app/db/postfix/certs/smtp.yourdomain.com.pem:/etc/ssl/certs/smtp.yourdomain.com.pem
      - /mnt/app/db/postfix/certs/smtp.yourdomain.com.key:/etc/ssl/private/smtp.yourdomain.com.key
      - /mnt/app/db/postfix/config/entrypoint.sh:/entrypoint.sh
      - /mnt/app/db/postfix/config/header_check:/etc/postfix/header_check
      - /mnt/app/db/postfix/config/sender_canonical_maps:/etc/postfix/sender_canonical_maps

  checkrr:
    container_name: checkrr
    image: aetaric/checkrr:latest
    ports:
      - 8585:8585/tcp
    volumes:
      - /mnt/app/db/checkrr/checkrr.yaml:/etc/checkrr.yaml
      - /mnt/app/db/checkrr:/config
      - /mnt/data/media:/media
    restart: unless-stopped

  rclone:
    image: rclone/rclone
    container_name: rclone
    ports:
      - 5572:5572/tcp
    volumes:
      - /mnt/app/db/rclone:/config/rclone
      - /mnt/app/db/rclone:/logs
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /dev/fuse:/dev/fuse
      - /mnt/data:/data
      - /mnt/app:/opt
      - /mnt/app/home/jon/compose/sys/rclone/rclone-daily.sh:/rclone-daily.sh
      - /tmp/rclone:/htmp
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    command: rcd -v --rc-web-gui --rc-web-gui-no-open-browser --rc-addr :5572 --rc-user rclone --rc-pass rclone --transfers=3 --copy-links
