services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/app/db/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - SERVER_REGIONS=SOME_REGION
      - SHADOWSOCKS=on
      - HTTPPROXY=on
      - OPENVPN_USER=user
      - OPENVPN_PASSWORD=pass
      - FIREWALL_OUTBOUND_SUBNETS=1.1.1.1/1
      - HTTP_CONTROL_SERVER_ADDRESS=:8000
    ports:
      - 8888:8888/tcp # HTTP
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 9117:9117/tcp # jackett
      - 8191:8191/tcp # flaresolverr
      - 9696:9696/tcp # prowlarr
      - 7474:7474/tcp # autobrr
      - 9000:9000/tcp # thelounge
      - 8000:8000 #control server
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
    volumes:
      - /mnt/app/db/jackett/config:/config
      - /mnt/app/db/jackett/downloads:/downloads
    network_mode: "service:gluetun"
    restart: unless-stopped
    depends_on:
      - gluetun

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
    volumes:
      - /mnt/app/db/prowlarr:/config
    network_mode: "service:gluetun"
    restart: unless-stopped
    depends_on:
      - gluetun

  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=999
      - PGID=999
    volumes:
      - /mnt/app/db/sonarr/config:/config
      - /mnt/app/db/sonarr/custom-cont-init.d:/custom-cont-init.d
      - /mnt/app/db/sonarr/custom-services.d:/custom-services.d
      - /mnt/data:/data
      - /mnt/app/download:/internal
    ports:
      - 8989:8989
    restart: unless-stopped

  sonarr4k:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr4k
    environment:
      - PUID=999
      - PGID=999
    volumes:
      - /mnt/app/db/sonarr4k/config:/config
      - /mnt/data:/data
      - /mnt/app/download:/internal
    ports:
      - 9090:9090
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:develop
    container_name: radarr
    environment:
      - PUID=999
      - PGID=999
    volumes:
      - /mnt/app/db/radarr/config:/config
      - /mnt/app/db/radarr/custom-cont-init.d:/custom-cont-init.d
      - /mnt/app/db/radarr/custom-services.d:/custom-services.d
      - /mnt/data:/data
      - /mnt/app/download:/internal
    ports:
      - 7878:7878 
    restart: unless-stopped

  radarr4k:
    image: lscr.io/linuxserver/radarr:develop
    container_name: radarr4k
    environment:
      - PUID=999
      - PGID=999
    volumes:
      - /mnt/app/db/radarr4k/config:/config
      - /mnt/data:/data
      - /mnt/app/download:/internal
    ports:
      - 7979:7979 
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:develop
    container_name: lidarr
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
    volumes:
      - /mnt/app/db/lidarr/config:/config
      - /mnt/app/db/lidarr/custom-services.d:/custom-services.d
      - /mnt/app/db/lidarr/custom-cont-init.d:/custom-cont-init.d
      - /mnt/data:/data
      - /mnt/app/download:/internal
      - /mnt/data/media/music-videos:/music-videos
      - /mnt/data/media/music-lidarr-extended:/downloads-lidarr-extended
    ports:
      - 8686:8686 
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
    volumes:
      - /mnt/app/db/bazarr/config:/config
      - /mnt/app/db/bazarr/subcleaner:/subcleaner
      - /mnt/data:/data
    ports:
      - 6767:6767
    restart: unless-stopped

  bazarr4k:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr4k
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
    volumes:
      - /mnt/app/db/bazarr4k/config:/config
      - /mnt/app/db/bazarr4k/subcleaner:/subcleaner
      - /mnt/data:/data
    ports:
      - 6868:6868
    restart: unless-stopped
      
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    user: 999:999
    environment:
      - TZ=Some/Region
    volumes:
      - /mnt/app/db/autobrr/config:/config
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  lounge:
    container_name: lounge
    image: ghcr.io/thelounge/thelounge:latest
    restart: unless-stopped
    volumes:
      - /mnt/app/db/lounge:/var/opt/thelounge
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  tautulli:
    image: tautulli/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
    volumes:
      - /mnt/app/db/tautulli/data:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  pmm: # Needs to be migrated to kometa
    image: meisnate12/plex-meta-manager:latest
    container_name: pmm
    environment:
      - PMM_CONFIG=/config/config.yml
      - PMM_TIME=10:00
    volumes:
      - /mnt/app/db/pmm:/config
      - ./pmm/r:/r
      - ./pmm/rc:/rc
      - ./pmm/ov:/ov
    restart: unless-stopped

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    environment:
      - TZ=Some/Region
    user: 999:999
    volumes:
      - /mnt/app/db/recyclarr:/config
        
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
    network_mode: "service:gluetun"
    restart: unless-stopped
    depends_on:
      - gluetun

  gluetun-qbt:
    image: qmcgaw/gluetun:latest
    container_name: gluetun-qbt
    environment:
      - VPN_PORT_FORWARDING=on
      - VPN_SERVICE_PROVIDER=private internet access
      - SERVER_REGIONS=SOME_REGION
      - SHADOWSOCKS=on
      - HTTPPROXY=on
      - OPENVPN_USER=user
      - OPENVPN_PASSWORD=pass
      - FIREWALL_OUTBOUND_SUBNETS=1.1.1.1/1
      - HTTP_CONTROL_SERVER_ADDRESS=:8001
    volumes:
      - /mnt/app/db/gluetun-qbt:/gluetun
    ports:
      - 6881:6881 #BT
      - 6881:6881/udp #qBT
      - 8081:8081 #qBT
      - 8001:8001 #control server
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  qbittorrent:
    #image: lscr.io/linuxserver/qbittorrent:latest
    image: lscr.io/linuxserver/qbittorrent:4.6.6-r0-ls348
    container_name: qbittorrent
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
      - WEBUI_PORT=8081
      - DOCKER_MODS=ghcr.io/t-anc/gsp-qbittorent-gluetun-sync-port-mod:main
      - GSP_QBT_ADDR=http://localhost:8081
      - GSP_GTN_ADDR=http://localhost:8001
      - GSP_GTN_API_KEY=keyy
    volumes:
      - /mnt/app/db/qbittorrent:/config
      - /mnt/app/download/qbittorrent:/data
    network_mode: "service:gluetun-qbt"
    depends_on:
      - gluetun-qbt
    restart: unless-stopped

  gluetun-nzb:
    image: qmcgaw/gluetun:latest
    container_name: gluetun-nzb
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - SERVER_REGIONS=SOME_REGION
      - SHADOWSOCKS=on
      - HTTPPROXY=on
      - OPENVPN_USER=user
      - OPENVPN_PASSWORD=pass
      - FIREWALL_OUTBOUND_SUBNETS=1.1.1.1/1
      - DNS_ADDRESS=9.9.9.9
      - HTTP_CONTROL_SERVER_ADDRESS=:8002
    volumes:
      - /mnt/app/db/gluetun-nzb:/gluetun
    ports:
      - 8085:8085 #sabnzbd
      - 8002:8002 #control server
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
    volumes:
      - /mnt/app/db/sabnzbd:/config
      - /mnt/app/download/sabnzbd:/downloads
    network_mode: "service:gluetun-nzb"
    depends_on:
      - gluetun-nzb
    restart: unless-stopped

  gluetun-nzb2:
    image: qmcgaw/gluetun:latest
    container_name: gluetun-nzb2
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - SERVER_REGIONS=SOME_REGION
      - SHADOWSOCKS=on
      - HTTPPROXY=on
      - OPENVPN_USER=user
      - OPENVPN_PASSWORD=pass
      - FIREWALL_OUTBOUND_SUBNETS=1.1.1.1/1
      - DNS_ADDRESS=9.9.9.9
      - HTTP_CONTROL_SERVER_ADDRESS=:8003
    volumes:
      - /mnt/app/db/gluetun-nzb2:/gluetun
    ports:
      - 8086:8085 #sabnzbd
      - 8003:8003 #control server
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  sabnzbd2:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd2
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
    volumes:
      - /mnt/app/db/sabnzbd2:/config
      - /mnt/app/download/sabnzbd2:/downloads2
    network_mode: "service:gluetun-nzb2"
    depends_on:
      - gluetun-nzb2
    restart: unless-stopped

  unpackerr:
    image: golift/unpackerr:latest
    container_name: unpackerr
    user: 999:999
    environment:
      - TZ=Some/Region
      - UN_LOG_FILE=/logs/unpackerr.log
      - UN_LOG_QUEUES=20m
      - UN_SONARR_0_URL=http://server.mylocal:8989
      - UN_SONARR_0_API_KEY=keyy
      - UN_SONARR_0_PROTOCOLS=torrent,usenet
      - UN_SONARR_1_URL=http://server.mylocal:9090
      - UN_SONARR_1_API_KEY=keyy
      - UN_SONARR_1_PROTOCOLS=torrent,usenet
      - UN_RADARR_0_URL=http://server.mylocal:7878
      - UN_RADARR_0_API_KEY=keyy
      - UN_RADARR_0_PROTOCOLS=torrent,usenet
      - UN_RADARR_1_URL=http://server.mylocal:7979
      - UN_RADARR_1_API_KEY=keyy
      - UN_RADARR_1_PROTOCOLS=torrent,usenet
      - UN_LIDARR_0_URL=http://server.mylocal:8686
      - UN_LIDARR_0_API_KEY=keyy
      - UN_LIDARR_0_PROTOCOLS=torrent,usenet
    volumes:
      - /mnt/app/download:/internal
      - /mnt/app/db/unpackerr/logs:/logs
    restart: unless-stopped

  tdarr:
    container_name: tdarr
   #image: ghcr.io/haveagitgat/tdarr:2.00.20.1
    image: ghcr.io/haveagitgat/tdarr:latest
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeName=server
    volumes:
      - /mnt/app/db/tdarr/server:/app/server
      - /mnt/app/db/tdarr/configs:/app/configs
      - /mnt/app/db/tdarr/logs:/app/logs
      - /mnt/transcode/tdarr:/temp
      - /mnt/data/media:/media
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
      - 8268:8268 # Example extra node port
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/dri:/dev/dri

  maintainerr:
    image: ghcr.io/jorenn92/maintainerr:latest
    container_name: maintainerr
    user: 999:1000
    volumes:
      - /mnt/app/db/maintainerr:/opt/data
      - /mnt/data/media:/media
    environment:
      - TZ=Some/Region
    ports:
      - 6246:6246
    restart: unless-stopped

  organizr:
    container_name: organizr
    image: organizr/organizr:latest
    ports:
      - 9393:80
    volumes:
      - /mnt/app/db/organizr:/config
    environment:
      - PUID=999
      - PGID=999
      - TZ=Some/Region
    restart: unless-stopped

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3001:3000
    volumes:
      - /mnt/app/db/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
      - /mnt/app/download:/internal:ro
      - /mnt/data/media:/data/media:ro
      - /mnt/transcode:/transcode:ro
