libraries:
  Movies:                                       # Each library must match the Plex library name
    collection_files:
      - file: config/Movies.yml                   # This is a local file on the system
      - file: config/seasonal.yml
  TV Shows:
    collection_files:
      - file: config/TVShows.yml
  Movies (4k):
    overlay_files:
      - file: config/overlays.yml
  TV Shows (4k):
    overlay_files:
      - file: config/overlays.yml

#  Music:
#    collection_files:
    #- file: config/Music.yml
    #playlist_files:
    #- file: config/playlists.yml

settings:

  run_order:
  - operations
  - metadata
  - collections
  - overlays
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: true
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: true
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_users: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  overlay_artwork_filetype: jpg
  overlay_artwork_quality: 75
plex:                                           # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://server.mylocal
  token: keyyy 
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:                                           # REQUIRED for the script to run
  apikey: keyyyy 
  language: en
  cache_expiration: 60
  region:
tautulli:                                       # Can be individually specified per library as well
  url: http://server.mylocal:8181
  apikey: keyyy 
omdb:
  apikey: keyy 
  cache_expiration: 60
mdblist:
  apikey: keeyyy 
  cache_expiration: 60
radarr:                                         # Can be individually specified per library as well
  url: http://server.mylocal:7878
  token: keeyyy 
  add_missing: true 
  add_existing: false
  root_folder_path: /data/media/movies
  monitor: true
  availability: announced
  quality_profile: Remux + WEB 1080p
  tag: pmm
  search: true 
  radarr_path:
  plex_path:
  upgrade_existing: false
sonarr:                                         # Can be individually specified per library as well
  url: http://server.mylocal:8989
  token: keyy 
  add_missing: true 
  add_existing: false
  root_folder_path: /data/media/tv
  monitor: all
  quality_profile: WEB-DL (1080p)
  language_profile: English
  series_type: standard
  season_folder: true
  tag: pmm
  search: true 
  cutoff_search: false
  sonarr_path:
  plex_path:
  upgrade_existing: false
########## GENERATED BY TRAKTAUTH ##########
trakt:
  client_id: iddd 
  client_secret: keyyy 
  authorization:
    access_token: <> 
    token_type: Bearer
    expires_in: 7889238
    refresh_token: <> 
    scope: public
    created_at: 1727501357
  pin:
############################################
