networks:
  zabbix:
    ipam:
      config:
        - subnet: 172.220.0.0/16
          gateway: 172.220.0.1

services:
  zabbix-proxy:
    container_name: zabbix-proxy
    image: zabbix/zabbix-proxy-mysql:alpine-latest
    restart: unless-stopped
    ports:
      - 10052:10051
    networks:
      zabbix:
        ipv4_address: 172.220.0.5
    environment:
      - ZBX_PROXYMODE=0
      - ZBX_HOSTNAME=server-proxy
      - ZBX_SERVER_HOST=10.100.0.2:10051
      - ZBX_STATSALLOWEDIP=10.100.0.2,127.0.0.1
      - DB_SERVER_HOST=mysql-server
      - DB_SERVER_PORT=3306
      - MYSQL_USER_FILE=/run/secrets/MYSQL_USER
      - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=zabbix
      - ZBX_CACHESIZE=256M
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_USER
      - MYSQL_ROOT_PASSWORD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 

  mysql-server:
    container_name: mysql-server
    image: mysql:8.0
    restart: unless-stopped
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - 3306:3306
    networks:
      - zabbix
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --skip-character-set-client-handshake
      - --default-authentication-plugin=mysql_native_password
      - --disable-log-bin
    volumes:
      - /mnt/app/db/zabbixproxy/var/lib/mysql:/var/lib/mysql:rw
    env_file:
      - ./env_vars/.env_db_mysql
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_USER
      - MYSQL_ROOT_PASSWORD

  db_data_mysql:
    container_name: db_data_mysql
    image: busybox
    networks:
      - zabbix

  zabbix-agent2:
    container_name: zabbix-agent2
    image: zabbix/zabbix-agent2:ubuntu-6.2-latest
    environment:
      - ZBX_HOSTNAME=server
      - ZBX_SERVER_HOST=172.220.0.1
      - ZBX_SERVER_PORT=10052
      - ZBX_DEBUGLEVEL=3
      - ZBX_ENABLEPERSISTENTBUFFER=true
    ports:
      - 10050:10050/tcp
      - 10051:10051/tcp
      - 31999:31999/tcp
    networks:
      - zabbix
    volumes:
      - /mnt/app/db/zabbixagent2/db:/var/lib/zabbix/buffer
      - /mnt/app/db/zabbixagent2/agentd.d:/etc/zabbix/zabbix_agentd.d
      - /mnt/app/db/zabbixagent2/sudoers:/etc/sudoers
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    privileged: true
    group_add:
      - "999" #add zabbix user to docker group within container

secrets:
  MYSQL_USER:
    file: ./env_vars/.MYSQL_USER
  MYSQL_PASSWORD:
    file: ./env_vars/.MYSQL_PASSWORD
  MYSQL_ROOT_USER:
    file: ./env_vars/.MYSQL_ROOT_USER
  MYSQL_ROOT_PASSWORD:
    file: ./env_vars/.MYSQL_ROOT_PASSWORD
