---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Plex:
    - Plex:
        icon: plex.png
        href: https://plex.yourdomain.com
        server: server-docker
        container: plex
        widget:
            type: plex
            url: https://plex.yourdomain.com
            key: keyyyy 

    - Tautulli:
        icon: tautulli.png
        href: http://server.mylocal:8181
        server: server-docker
        container: tautulli
        widget:
            type: tautulli
            url: http://server.mylocal:8181
            key: keyyyy 

    - TrueNAS:
        icon: truenas.png
        href: http://server.mylocal:81
        widget:
            type: truenas
            url: http://server.mylocal:81
            key: keyyyyyy 
            fields: ["load", "uptime", "alerts"]

- Media Management:
    - Radarr:
        icon: radarr.png
        href: http://server.mylocal:7878
        server: server-docker
        container: radarr
        widget:
            type: radarr
            url: http://server.mylocal:7878
            key: keyyyy 
#           fields: ["wanted", "missing", "queued", "movies"]
            fields: ["queued"]

    - Radarr (4k):
        icon: radarr.png
        href: http://server.mylocal:7979
        server: server-docker
        container: radarr4k
        widget:
            type: radarr
            url: http://server.mylocal:7979
            key: keyyy 
#           fields: ["wanted", "missing", "queued", "movies"]
            fields: ["queued"]

    - Sonarr:
        icon: sonarr.png
        href: http://server.mylocal:8989
        server: server-docker
        container: sonarr
        widget:
            type: sonarr
            url: http://server.mylocal:8989
            key: keyyy 
#           fields: ["wanted", "queued", "series"]
            fields: ["queued"]

    - Sonarr (4k):
        icon: sonarr.png
        href: http://server.mylocal:9090
        server: server-docker
        container: sonarr4k
        widget:
            type: sonarr
            url: http://server.mylocal:9090
            key: keyyy 
#           fields: ["wanted", "queued", "series"]
            fields: ["queued"]

    - Lidarr:
        icon: lidarr.png
        href: http://server.mylocal:8686
        server: server-docker
        container: lidarr
        widget:
            type: lidarr
            url: http://server.mylocal:8686
            key: keyyy 
#           fields: ["wanted", "missing", "queued", "albums"]
            fields: ["queued"]

    - Bazarr:
        icon: bazarr.png
        href: http://server.mylocal:6767
        server: server-docker
        container: bazarr
        widget:
            type: bazarr
            url: http://server.mylocal:6767
            key: keyyy 
            fields: ["missingEpisodes", "missingMovies"]

    - Bazarr (4k):
        icon: bazarr.png
        href: http://server.mylocal:6868
        server: server-docker
        container: bazarr4k
        widget:
            type: bazarr
            url: http://server.mylocal:6868
            key: keyyy 
            fields: ["missingEpisodes", "missingMovies"]

- Requests & Downloads:
    - Overseerr:
        icon: overseerr.png
        href: https://overseerr.yourdomain.com
        server: server-docker
        container: overseerr
        widget:
            type: overseerr
            url: https://overseerr.yourdomain.com
            key: keyyy 
#           fields: ["pending", "approved", "available", "processing"]
            fields: ["approved", "processing"]

    - sabnzbd 1:
        icon: sabnzbd 
        href: http://server.mylocal:8085/sabnzbd
        server: server-docker
        container: sabnzbd
        widget:
            type: sabnzbd
            url: http://server.mylocal:8085/sabnzbd
            key: keyyy 
            fields: ["rate", "queue", "timeleft"]

    - sabnzbd 2:
        icon: sabnzbd 
        href: http://server.mylocal:8086/sabnzbd
        server: server-docker
        container: sabnzbd2
        widget:
            type: sabnzbd
            url: http://server.mylocal:8086/sabnzbd
            key: keyyy 
            fields: ["rate", "queue", "timeleft"]

    - qBittorrent:
        icon: qbittorrent 
        href: http://server.mylocal:8081
        server: server-docker
        container: qbittorrent 
        widget:
            type: qbittorrent
            url: http://server.mylocal:8081
            user: user 
            password: pass 
            fields: ["leech", "download", "seed", "upload"]

    - Autobrr:
        icon: autobrr.png
        href: http://server.mylocal:7474
        server: server-docker
        container: autobrr
        widget:
            type: autobrr
            url: http://server.mylocal:7474
            key: keyyy 
#           fields: ["approvedPushes", "rejectedPushes", "filters", "indexers"]
            fields: ["approvedPushes", "rejectedPushes"]

    - Tdarr:
        icon: tdarr.png
        href: http://server.mylocal:8265
        server: server-docker
        container: tdarr 
        widget:
            type: tdarr 
            url: http://server.mylocal:8265
#           fields: ["queue", "processed", "errored", "saved"]
            fields: ["queue", "errored"]

#  - Prowlarr:
#      icon: prowlarr 
#      href: http://server.mylocal:9696
#      server: server-docker
#      container: prowlarr 
#      widget:
#        type: prowlarr 
#        url: http://server.mylocal:9696
#        key: keyy 
#        fields: ["numberOfGrabs", "numberOfQueries" ]

#  - Jackett:
#      icon: jackett 
#      href: http://server.mylocal:9117
#      server: server-docker
#      container: jackett 
#      widget:
#        type: jackett 
#        url: http://server.mylocal:9117
#        fields: ["configured", "errored"]

- Networking:
    - gluetun:
        icon: gluetun
        server: server-docker
        container: gluetun
        widget:
            type: gluetun
            url: http://server.mylocal:8000
            key: keyyy 
            fields: ["public_ip", "region", "country"]

    - gluetun (nzb1):
        icon: gluetun
        server: server-docker
        container: gluetun-nzb
        widget:
            type: gluetun
            url: http://server.mylocal:8002
            key: keyy 
            fields: ["public_ip", "region", "country"]

    - gluetun (nzb2):
        icon: gluetun
        href: http://server.mylocal:8086/sabnzbd
        server: server-docker
        container: gluetun-nzb2
        widget:
            type: gluetun
            url: http://server.mylocal:8003
            key: keyy 
            fields: ["public_ip", "region", "country"]

    - gluetun (qbt):
        icon: gluetun
        server: server-docker
        container: gluetun-qbt
        widget:
            type: gluetun
            url: http://server.mylocal:8001
            key: keyy 
            fields: ["public_ip", "region", "country"]

    - Traefik:
        icon: traefik.png
        href: http://server.mylocal:8282
        server: server-docker
        container: traefik
        widget:
            type: traefik
            url: http://server.mylocal:8282
            fields: ["routers", "services", "middleware"]
